### ISSUE TITLE
Start page image is not visible on Firefox

### ISSUE THREAD

**Issue by jgosar** [outbrain/cv-boostifier#6]
Start page image is not visible on Firefox
Tested in Firefox 81.0 on Ubuntu.

![image](https://user-images.githubusercontent.com/36840705/95041396-dcac9d00-06d6-11eb-814e-2d92fa9a197b.png)

**Comment by dsternlicht** [comment]
👍🏻 We'll check.

Thanks for reporting :)

**Comment by dsternlicht** [comment]
We've redesigned the whole homepage. Closing this issue.
